version: '3.8'
services:
  api:
    build: .
    container_name: "spukify-api"
    expose:
      - 8080
    volumes:
      - ./app:/app
    depends_on:
      - spukify-db

  spukify-db:
    image: postgres:15-alpine
    container_name: "spukify-db"
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=spukify
      - POSTGRES_PASSWORD=spukify
      - POSTGRES_DB=spukify

volumes:
  postgres_data:
