services:
  api:
    build: .
    container_name: "spukify-api"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      - spukify-db
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  spukify-db:
    image: postgres:15-alpine
    container_name: "spukify-db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=spukify
      - POSTGRES_PASSWORD=spukify
      - POSTGRES_DB=spukify

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - spukify-db

volumes:
  postgres_data:
